name: Daily Parking Registration

on:
  schedule:
    - cron: '0 17 * * *'  # Run at 12 PM CDT / 11 AM CST (5 PM UTC)
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  register-parking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@master
        
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium python-dotenv
          
      - name: Run parking registration script
        env:
          PROPERTY_NAME: ${{ secrets.PROPERTY_NAME }}
          UNIT_NUMBER: ${{ secrets.UNIT_NUMBER }}
          RESIDENT_NAME: ${{ secrets.RESIDENT_NAME }}
          GUEST_NAME: ${{ secrets.GUEST_NAME }}
          GUEST_PHONE: ${{ secrets.GUEST_PHONE }}
          VEHICLE_MAKE: ${{ secrets.VEHICLE_MAKE }}
          VEHICLE_MODEL: ${{ secrets.VEHICLE_MODEL }}
          VEHICLE_PLATE: ${{ secrets.VEHICLE_PLATE }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: python register_parking.py